version: '3'
services:
  gql-schema-registry-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schema_registry
    ports:
      - 6000:5432
    volumes:
      - gql-schema-registry-db-volume:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d schema_registry']
      timeout: 5s
      retries: 10
    networks:
      gql-schema:
        aliases:
          - 'gql-schema-registry-db'

  gql-schema-registry-redis:
    image: redis:8-alpine
    ports:
      - 6004:6379
    command: redis-server --requirepass password
    environment:
      SERVICE_NAME: 'gql-schema-registry-redis'
    networks:
      gql-schema:
        aliases:
          - 'gql-schema-registry-redis'

networks:
  gql-schema:

volumes:
  gql-schema-registry-db-volume:
