version: '3'
services:
  gql-schema-registry:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ./node_modules/.bin/ts-node src/schema-registry.ts
    ports:
      - 6001:3000
      - 6002:5850
    environment:
      - ENV_ID=dev
      - WITH_WEBPACK=${WITH_WEBPACK-1}
      - DB_SCHEMA_REGISTRY=gql-schema-registry-db
      - NODE_ENV=production
      - REDIS_HOST=gql-schema-registry-redis
      - REDIS_SECRET=password
    volumes:
      - .:/app/
    restart: always
    depends_on:
      - gql-schema-registry-redis
      - gql-schema-registry-db
    networks:
      gql-schema:
        aliases:
          - 'gql-schema-registry'
networks:
  gql-schema:

volumes:
  gql-schema-registry-db-volume:
