version: '3'
services:
  gql-schema-registry:
    image: pipedrive/graphql-schema-registry:latest
    ports:
      - 6001:3000
      - 6002:5850
    environment:
      - WITH_WEBPACK=${WITH_WEBPACK-1}
      - DB_SCHEMA_REGISTRY=gql-schema-registry-db
    restart: always
    depends_on:
      - gql-schema-registry-redis
      - gql-schema-registry-db
    networks:
      gql-schema:
        aliases:
          - 'gql-schema-registry'

networks:
  gql-schema:

volumes:
  gql-schema-registry-db-volume:
