CREATE TABLE IF NOT EXISTS persisted_queries (
    id BIGSERIAL PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    query TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    updated_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    added_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
    is_active INTEGER NOT NULL DEFAULT 1,
    updated_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    added_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "schema" (
    id BIGSERIAL PRIMARY KEY,
    service_id BIGINT NULL REFERENCES services(id) ON DELETE CASCADE ON UPDATE CASCADE,
    is_active INTEGER NOT NULL DEFAULT 1,
    type_defs TEXT,
    added_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS container_schema (
    id BIGSERIAL PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE ON UPDATE CASCADE,
    schema_id BIGINT NOT NULL REFERENCES "schema"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    version VARCHAR(100) NOT NULL DEFAULT '',
    added_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (service_id, version)
);

CREATE INDEX IF NOT EXISTS idx_schema_service_id ON "schema"(service_id);
CREATE INDEX IF NOT EXISTS idx_container_schema_schema_id ON container_schema(schema_id);
