module.exports = {
	rootDir: '../..',
	resetModules: true,
	restoreMocks: true,
	clearMocks: true,
	maxWorkers: 1,
	globalSetup: '<rootDir>/test/integration/globalSetup.ts',
	preset: 'ts-jest',
	testEnvironment: 'node',
	testMatch: [
		'<rootDir>/test/integration/**/*.test.ts',
		'<rootDir>/src/**/*.itest.ts',
	],
	moduleFileExtensions: ['ts', 'js', 'json'],
	modulePathIgnorePatterns: ['<rootDir>/app/'],
	verbose: true,
	resetMocks: true,
	collectCoverage: false,
	modulePaths: ['<rootDir>'],
};
