name: Functional Tests

on:
  push:
    branches:
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read
  statuses: write
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm build

      - name: Start containers
        run: docker-compose -f "docker-compose.functional.yml" up -d --build

      - name: Run tests
        run: npm run test-functional

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
