name: Integration tests
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read
  statuses: write
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'npm'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: npm run build
      - run: npm run test:unit:coverage
      - run: npm run test:unit:frontend:coverage

      - name: Start containers
        run: docker-compose -f "docker-compose.base.yml" -f "docker-compose.functional.yml" up -d

      - run: npm run test:integration:coverage
      - run: npm run test:coverage:merge
      - name: Publish coverage to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.base.yml" -f "docker-compose.functional.yml" down
